"""Public item and vehicle recipes shared by commands, services and guides."""

from typing import Any, Dict
from .air_dominance import JETS, recipe

ARMORED_MODELS = ("m1a2", "leopard2a7")
B52_REPAIR_COST_PCTS = (25, 50, 75)
B52_REPAIR_HOURS = (1, 2, 3)
VEHICLE_CATALOG: Dict[str, Dict[str, Any]] = {
    "b2": {
        "label": "Northrop Grumman B-2 Spirit",
        "short": "B-2 Spirit",
        "emoji": "🦇",
        "cost": "vehicle_b2_cost",
        "build": "vehicle_b2_build_hours",
        "fallback_cost": 15000000000,
        "fallback_build": 5,
        "role": "offense",
    },
    "b52": {
        "label": "Boeing B-52H Stratofortress",
        "short": "B-52H Stratofortress",
        "emoji": "💣",
        "cost": "vehicle_b52_cost",
        "build": "vehicle_b52_build_hours",
        "fallback_cost": 1000000000,
        "fallback_build": 8,
        "role": "offense",
        "ammo": "Mk 82 500-lb General-Purpose Bomb Stick",
        "ammo_cost": "vehicle_b52_ammo_cost",
        "load": "vehicle_b52_load_minutes",
        "cap": "vehicle_b52_ammo_cap",
        "cooldown": "vehicle_b52_cooldown_minutes",
        "fallback_ammo_cost": 50000000,
        "fallback_load": 30,
        "fallback_cap": 2,
    },
    "u2": {
        "label": "Lockheed U-2S Dragon Lady",
        "short": "U-2S Dragon Lady",
        "emoji": "🔭",
        "cost": "vehicle_u2_cost",
        "build": "vehicle_u2_build_hours",
        "fallback_cost": 250000000,
        "fallback_build": 8,
        "role": "offense",
    },
    "deimos": {
        "label": "F3 DeathMARK Tracker",
        "short": "F3 DeathMARK Tracker",
        "emoji": "☠️",
        "cost": "vehicle_deimos_cost",
        "build": "vehicle_deimos_build_hours",
        "fallback_cost": 80000000,
        "fallback_build": 2,
        "role": "offense",
    },
    "sr71": {
        "label": "Lockheed SR-71A Blackbird",
        "short": "SR-71A Blackbird",
        "emoji": "🛫",
        "cost": "vehicle_sr71_cost",
        "build": "vehicle_sr71_build_hours",
        "fallback_cost": 400000000,
        "fallback_build": 4,
        "role": "offense",
    },
    "zumwalt": {
        "label": "Zumwalt-class DDG-1000 EMRG Technology Demonstrator",
        "short": "DDG-1000 EMRG",
        "emoji": "⚓",
        "cost": "vehicle_zumwalt_cost",
        "build": "vehicle_zumwalt_build_hours",
        "fallback_cost": 700000000,
        "fallback_build": 8,
        "role": "offense",
        "ammo": "Hyper Velocity Projectile",
        "ammo_cost": "vehicle_zumwalt_ammo_cost",
        "load": "vehicle_zumwalt_load_minutes",
        "cap": "vehicle_zumwalt_ammo_cap",
        "cooldown": "vehicle_zumwalt_cooldown_minutes",
        "fallback_ammo_cost": 55000000,
        "fallback_load": 10,
        "fallback_cap": 3,
    },
    "virginia": {
        "label": "Virginia-class Block V Attack Submarine",
        "short": "Virginia-class Block V SSN",
        "emoji": "🌊",
        "cost": "vehicle_virginia_cost",
        "build": "vehicle_virginia_build_hours",
        "fallback_cost": 800000000,
        "fallback_build": 12,
        "role": "offense",
        "ammo": "Mk 48 Mod 7 ADCAP",
        "ammo_cost": "vehicle_virginia_ammo_cost",
        "load": "vehicle_virginia_load_minutes",
        "cap": "vehicle_virginia_ammo_cap",
        "cooldown": "vehicle_virginia_cooldown_minutes",
        "fallback_ammo_cost": 45000000,
        "fallback_load": 10,
        "fallback_cap": 3,
    },
    "himars": {
        "label": "M142 High Mobility Artillery Rocket System",
        "short": "M142 HIMARS",
        "emoji": "🚀",
        "cost": "vehicle_himars_cost",
        "build": "vehicle_himars_build_hours",
        "fallback_cost": 250000000,
        "fallback_build": 4,
        "role": "offense",
        "ammo": "M31A2 GMLRS rocket",
        "ammo_cost": "vehicle_himars_ammo_cost",
        "load": "vehicle_himars_load_minutes",
        "cap": "vehicle_himars_ammo_cap",
        "cooldown": "vehicle_himars_cooldown_minutes",
        "fallback_ammo_cost": 20000000,
        "fallback_load": 0,
        "fallback_cap": 5,
    },
    "apache": {
        "label": "Boeing AH-64E Apache Guardian",
        "short": "AH-64E Apache Guardian",
        "emoji": "🚁",
        "cost": "vehicle_apache_cost",
        "build": "vehicle_apache_build_hours",
        "fallback_cost": 200000000,
        "fallback_build": 2,
        "role": "offense",
        "ammo": "AGM-179A Joint Air-to-Ground Missile",
        "ammo_cost": "vehicle_apache_ammo_cost",
        "load": "vehicle_apache_load_minutes",
        "cap": "vehicle_apache_ammo_cap",
        "cooldown": "vehicle_apache_cooldown_minutes",
        "fallback_ammo_cost": 15000000,
        "fallback_load": 5,
        "fallback_cap": 6,
    },
    "mq9": {
        "label": "General Atomics MQ-9B SkyGuardian",
        "short": "MQ-9B SkyGuardian",
        "emoji": "🛩️",
        "cost": "vehicle_mq9_cost",
        "build": "vehicle_mq9_build_hours",
        "fallback_cost": 150000000,
        "fallback_build": 3,
        "role": "offense",
        "ammo": "AGM-114R Hellfire II",
        "ammo_cost": "vehicle_mq9_ammo_cost",
        "load": "vehicle_mq9_load_minutes",
        "cap": "vehicle_mq9_ammo_cap",
        "cooldown": "vehicle_mq9_cooldown_minutes",
        "fallback_ammo_cost": 10000000,
        "fallback_load": 0,
        "fallback_cap": 5,
    },
    "f15e": {
        "label": "Boeing F-15E Strike Eagle",
        "short": "F-15E Strike Eagle",
        "emoji": "🦅",
        "cost": "vehicle_f15e_cost",
        "build": "vehicle_f15e_build_hours",
        "fallback_cost": 400000000,
        "fallback_build": 7,
        "role": "offense",
        "ammo": "AGM-158B JASSM-ER",
        "ammo_cost": "vehicle_f15e_ammo_cost",
        "load": "vehicle_f15e_load_minutes",
        "cap": "vehicle_f15e_ammo_cap",
        "cooldown": "vehicle_f15e_cooldown_minutes",
        "fallback_ammo_cost": 40000000,
        "fallback_load": 10,
        "fallback_cap": 3,
    },
    "a10": {
        "label": "Fairchild Republic A-10C Thunderbolt II",
        "short": "A-10C Thunderbolt II",
        "emoji": "🐗",
        "cost": "vehicle_a10_cost",
        "build": "vehicle_a10_build_hours",
        "fallback_cost": 12000000000,
        "fallback_build": 12,
        "role": "offense",
        "ammo": "A-10C II CAS Strike Package",
        "ammo_cost": "vehicle_a10_ammo_cost",
        "load": "vehicle_a10_load_minutes",
        "cap": "vehicle_a10_ammo_cap",
        "cooldown": "vehicle_a10_cooldown_minutes",
        "fallback_ammo_cost": 1000000000,
        "fallback_load": 60,
        "fallback_cap": 2,
    },
    "su34": {
        "label": "Sukhoi Su-34 Fullback",
        "short": "Su-34 Fullback",
        "emoji": "🦆",
        "cost": "vehicle_su34_cost",
        "build": "vehicle_su34_build_hours",
        "fallback_cost": 18000000000,
        "fallback_build": 16,
        "role": "offense",
        "ammo": "Kh-38ML / KAB-500S Interdiction Package",
        "ammo_cost": "vehicle_su34_ammo_cost",
        "load": "vehicle_su34_load_minutes",
        "cap": "vehicle_su34_ammo_cap",
        "cooldown": "vehicle_su34_cooldown_minutes",
        "fallback_ammo_cost": 1500000000,
        "fallback_load": 90,
        "fallback_cap": 2,
    },
    "c130j": {
        "label": "Lockheed Martin C-130J-30 Super Hercules / Rapid Dragon",
        "short": "C-130J Rapid Dragon",
        "emoji": "📦",
        "cost": "vehicle_c130j_cost",
        "build": "vehicle_c130j_build_hours",
        "fallback_cost": 900000000,
        "fallback_build": 5,
        "role": "offense",
        "ammo": "Rapid Dragon AGM-158B pallet",
        "ammo_cost": "vehicle_c130j_ammo_cost",
        "load": "vehicle_c130j_load_minutes",
        "cap": "vehicle_c130j_ammo_cap",
        "cooldown": "vehicle_c130j_cooldown_minutes",
        "fallback_ammo_cost": 120000000,
        "fallback_load": 20,
        "fallback_cap": 3,
    },
    "champ": {
        "label": "Boeing CHAMP High-Power Microwave Mission System",
        "short": "CHAMP Microwave System",
        "emoji": "⚡",
        "cost": "vehicle_champ_cost",
        "build": "vehicle_champ_build_hours",
        "fallback_cost": 650000000,
        "fallback_build": 4,
        "role": "offense",
        "ammo": "CHAMP AGM-86B microwave cruise missile",
        "ammo_cost": "vehicle_champ_ammo_cost",
        "load": "vehicle_champ_load_minutes",
        "cap": "vehicle_champ_ammo_cap",
        "cooldown": "vehicle_champ_cooldown_minutes",
        "fallback_ammo_cost": 100000000,
        "fallback_load": 20,
        "fallback_cap": 2,
    },
    "maldx": {
        "label": "ADM-160 MALD-X Networked Decoy Launch Cell",
        "short": "ADM-160 MALD-X",
        "emoji": "👻",
        "cost": "vehicle_maldx_cost",
        "build": "vehicle_maldx_build_hours",
        "fallback_cost": 350000000,
        "fallback_build": 2,
        "role": "offense",
        "ammo": "ADM-160C MALD-X networked decoy",
        "ammo_cost": "vehicle_maldx_ammo_cost",
        "load": "vehicle_maldx_load_minutes",
        "cap": "vehicle_maldx_ammo_cap",
        "cooldown": "vehicle_maldx_cooldown_minutes",
        "fallback_ammo_cost": 50000000,
        "fallback_load": 10,
        "fallback_cap": 5,
    },
    "lrhw": {
        "label": "Long-Range Hypersonic Weapon (LRHW) Dark Eagle Battery",
        "short": "LRHW Dark Eagle",
        "emoji": "🔥",
        "cost": "vehicle_lrhw_cost",
        "build": "vehicle_lrhw_build_hours",
        "fallback_cost": 1200000000,
        "fallback_build": 6,
        "role": "offense",
        "ammo": "C-HGB All-Up Round",
        "ammo_cost": "vehicle_lrhw_ammo_cost",
        "load": "vehicle_lrhw_load_minutes",
        "cap": "vehicle_lrhw_ammo_cap",
        "cooldown": "vehicle_lrhw_cooldown_minutes",
        "fallback_ammo_cost": 250000000,
        "fallback_load": 30,
        "fallback_cap": 2,
    },
    "xb70": {
        "label": "North American XB-70 Valkyrie",
        "short": "XB-70 Valkyrie",
        "emoji": "🧊",
        "cost": "vehicle_xb70_cost",
        "build": "vehicle_xb70_build_hours",
        "fallback_cost": 3200000000,
        "fallback_build": 10,
        "role": "offense",
        "ammo": "B53 strategic gravity bomb",
        "ammo_cost": "vehicle_xb70_ammo_cost",
        "load": "vehicle_xb70_load_minutes",
        "cap": "vehicle_xb70_ammo_cap",
        "cooldown": "vehicle_xb70_cooldown_minutes",
        "fallback_ammo_cost": 250000000,
        "fallback_load": 45,
        "fallback_cap": 1,
    },
    "m1a2": {
        "label": "General Dynamics M1A2 SEPv3 Abrams",
        "short": "M1A2 SEPv3 Abrams",
        "emoji": "🛞",
        "cost": "vehicle_m1a2_cost",
        "build": "vehicle_m1a2_build_hours",
        "fallback_cost": 750000000,
        "fallback_build": 6,
        "role": "offense",
        "ammo": "M829A4 APFSDS-T",
        "ammo_cost": "vehicle_m1a2_ammo_cost",
        "load": "vehicle_m1a2_load_minutes",
        "cap": "vehicle_m1a2_ammo_cap",
        "cooldown": "vehicle_m1a2_cooldown_minutes",
        "fallback_ammo_cost": 40000000,
        "fallback_load": 20,
        "fallback_cap": 6,
    },
    "leopard2a7": {
        "label": "Krauss-Maffei Wegmann Leopard 2A7A1",
        "short": "Leopard 2A7A1",
        "emoji": "🐆",
        "cost": "vehicle_leopard2a7_cost",
        "build": "vehicle_leopard2a7_build_hours",
        "fallback_cost": 750000000,
        "fallback_build": 6,
        "role": "offense",
        "ammo": "DM63 APFSDS-T",
        "ammo_cost": "vehicle_leopard2a7_ammo_cost",
        "load": "vehicle_leopard2a7_load_minutes",
        "cap": "vehicle_leopard2a7_ammo_cap",
        "cooldown": "vehicle_leopard2a7_cooldown_minutes",
        "fallback_ammo_cost": 40000000,
        "fallback_load": 20,
        "fallback_cap": 6,
    },
    "aegis": {
        "label": "Arleigh Burke-class Flight III Aegis Destroyer",
        "short": "Flight III Aegis",
        "emoji": "🛡️",
        "cost": "vehicle_aegis_cost",
        "build": "vehicle_aegis_build_hours",
        "fallback_cost": 550000000,
        "fallback_build": 8,
        "role": "defense",
        "ammo": "RIM-174B SM-6",
        "ammo_cost": "vehicle_aegis_ammo_cost",
        "load": "vehicle_aegis_load_minutes",
        "cap": "vehicle_aegis_ammo_cap",
        "fallback_ammo_cost": 25000000,
        "fallback_load": 0,
        "fallback_cap": 3,
    },
    "p8": {
        "label": "Boeing P-8A Poseidon",
        "short": "P-8A Poseidon",
        "emoji": "🔎",
        "cost": "vehicle_p8_cost",
        "build": "vehicle_p8_build_hours",
        "fallback_cost": 450000000,
        "fallback_build": 8,
        "role": "defense",
        "ammo": "Mk 54 lightweight torpedo",
        "ammo_cost": "vehicle_p8_ammo_cost",
        "load": "vehicle_p8_load_minutes",
        "cap": "vehicle_p8_ammo_cap",
        "fallback_ammo_cost": 25000000,
        "fallback_load": 0,
        "fallback_cap": 3,
    },
    "patriot": {
        "label": "MIM-104 Patriot PAC-3 MSE Battery",
        "short": "Patriot PAC-3 MSE",
        "emoji": "📡",
        "cost": "vehicle_patriot_cost",
        "build": "vehicle_patriot_build_hours",
        "fallback_cost": 350000000,
        "fallback_build": 5,
        "role": "defense",
        "ammo": "PAC-3 MSE interceptor",
        "ammo_cost": "vehicle_patriot_ammo_cost",
        "load": "vehicle_patriot_load_minutes",
        "cap": "vehicle_patriot_ammo_cap",
        "fallback_ammo_cost": 25000000,
        "fallback_load": 0,
        "fallback_cap": 3,
    },
    "javelin": {
        "label": "FGM-148F Javelin Anti-Armor Team",
        "short": "FGM-148F Javelin Team",
        "emoji": "🎯",
        "cost": "vehicle_javelin_cost",
        "build": "vehicle_javelin_build_hours",
        "fallback_cost": 200000000,
        "fallback_build": 3,
        "role": "defense",
        "ammo": "FGM-148F Javelin missile",
        "ammo_cost": "vehicle_javelin_ammo_cost",
        "load": "vehicle_javelin_load_minutes",
        "cap": "vehicle_javelin_ammo_cap",
        "fallback_ammo_cost": 25000000,
        "fallback_load": 15,
        "fallback_cap": 4,
    },
}
VEHICLE_CATALOG.update({model: recipe(model) for model in JETS})
DEPLOYABLE_VEHICLES = (
    "b2",
    "b52",
    "u2",
    "deimos",
    "sr71",
    "zumwalt",
    "virginia",
    "himars",
    "apache",
    "mq9",
    "f15e",
    "a10",
    "su34",
    "c130j",
    "champ",
    "maldx",
    "lrhw",
    "xb70",
    "m1a2",
    "leopard2a7",
    *JETS,
)
LOADABLE_VEHICLES = (
    "b52",
    "zumwalt",
    "virginia",
    "himars",
    "apache",
    "mq9",
    "f15e",
    "a10",
    "su34",
    "c130j",
    "champ",
    "maldx",
    "lrhw",
    "xb70",
    "m1a2",
    "leopard2a7",
    "aegis",
    "p8",
    "patriot",
    "javelin",
    *JETS,
)
CONVENTIONAL_AMMO_TARGETS: Dict[str, str] = {
    "regular-aa": "Radar AA rockets",
    "s400": "S-400 40N6E interceptors",
    "b52": "B-52 Mk 82 bomb sticks",
    "zumwalt": "Zumwalt Hyper Velocity Projectiles",
    "virginia": "Virginia Mk 48 torpedoes",
    "himars": "HIMARS M31A2 rockets",
    "apache": "Apache/Comanche AGM-179A JAGMs",
    "mq9": "MQ-9B AGM-114R Hellfires",
    "f15e": "F-15E AGM-158B JASSM-ERs",
    "a10": "A-10C II CAS strike packages",
    "su34": "Su-34 Kh-38ML/KAB-500S interdiction packages",
    "c130j": "Rapid Dragon pallets",
    "champ": "CHAMP microwave missiles",
    "maldx": "MALD-X decoys",
    "lrhw": "Dark Eagle C-HGB rounds",
    "xb70": "XB-70 B53 bombs",
    "m1a2": "M1A2 M829A4 APFSDS-T rounds",
    "leopard2a7": "Leopard 2A7A1 DM63 APFSDS-T rounds",
    "aegis": "Aegis RIM-174B SM-6 missiles",
    "p8": "P-8A Mk 54 torpedoes",
    "patriot": "Patriot PAC-3 MSE interceptors",
    "javelin": "FGM-148F Javelin missiles",
}
CONVENTIONAL_AMMO_TARGETS.update({model: recipe(model)["ammo"] for model in JETS})
CONSUMABLES: Dict[str, Dict[str, str]] = {
    "lock": {
        "name": "Lock",
        "emoji": "🔒",
        "price_key": "price_lock",
        "blurb": "Auto-blocks a steal (45%) or a bank heist (15%). Consumed when it blocks.",
    },
    "uno": {
        "name": "Uno Reverse",
        "emoji": "🔄",
        "price_key": "price_uno",
        "blurb": "Auto-reverses a steal (25%) or vault raid (10%): the thief pays you 75% of the attempted theft, capped at 10% of their wallet + bank. Consumed on trigger; transfers existing funds only.",
    },
    "copcall": {
        "name": "Cop Call",
        "emoji": "🚓",
        "price_key": "price_copcall",
        "blurb": "Use on someone to jail them from stealing for a while.",
    },
    "drill": {
        "name": "Majin Drill",
        "emoji": "🔩",
        "price_key": "price_drill",
        "blurb": "Required to /robbank a vault. Consumed on the attempt, win or lose.",
    },
    "getaway": {
        "name": "Getaway Car",
        "emoji": "🚗",
        "price_key": "price_getaway",
        "blurb": "Use `/getaway` to instantly break out of jail. Consumed on use.",
    },
}
PERMANENT_UTILITIES: Dict[str, Dict[str, str]] = {
    "android21helper": {
        "name": "Android 21 Autonomous Helper",
        "emoji": "🦾",
        "price_key": "android21_helper_price",
        "blurb": "Works your active career around the clock at 70% base salary, paid straight to your wallet. Automatic shifts earn +1 XP but no decision bonus or five-shift payday. Paid certification via /job licences adds 25% of your certified licence allowance, without manual-shift credit.",
        "image": "android21-autonomous-helper.png",
    }
}
COMANCHE_AMMO_TARGETS: Dict[str, str] = {
    "icbm": "completed ICBMs",
    "b61": "B-2 B61-12 payload",
    "radar-aa": "loaded and reserve Radar AA rockets",
    "s400": "S-400 40N6E interceptors",
    "b52": "B-52 Mk 82 bomb sticks",
    "zumwalt": "Zumwalt Hyper Velocity Projectiles",
    "virginia": "Virginia Mk 48 torpedoes",
    "himars": "HIMARS M31A2 rockets",
    "apache": "Apache/Comanche AGM-179A JAGMs",
    "mq9": "MQ-9B AGM-114R Hellfires",
    "f15e": "F-15E AGM-158B JASSM-ERs",
    "a10": "A-10C II CAS strike packages",
    "su34": "Su-34 Kh-38ML/KAB-500S interdiction packages",
    "aegis": "Aegis RIM-174B SM-6 missiles",
    "p8": "P-8A Mk 54 torpedoes",
    "patriot": "Patriot PAC-3 MSE interceptors",
    "m1a2": "M1A2 M829A4 APFSDS-T rounds",
    "javelin": "FGM-148F Javelin missiles",
}
COMANCHE_AMMO_TARGETS.update({model: recipe(model)["ammo"] for model in JETS})
ITEM_HOLD_CAPS: Dict[str, str] = {
    "lock": "hold_cap_lock",
    "uno": "hold_cap_uno",
    "copcall": "hold_cap_copcall",
    "getaway": "hold_cap_getaway",
    "drill": "hold_cap_drill",
}
